### ISSUE TITLE
Java icon trademark

### ISSUE THREAD

**Issue by HaasJona** [CleoMenezes/Custom-Adwaita-Folder-Icons#1]
The Coffee cup is an Oracle trademark, probably can't be used with the MIT license, and also represents Oracle Java instead of Java in itself or OpenJdk.

Look at https://wiki.openjdk.java.net/display/duke/Main for proper logos, like maybe the OpenJDK logo in the header bar or an image of [Duke](https://commons.wikimedia.org/wiki/File:Duke_%28Java_mascot%29_waving.svg), which is an open source icon/mascot representing Java.

**Comment by CleoMenezesJr** [comment]
Thanks for the warning. I deleted the Java logo and put the Duke icon. You can check it here: https://github.com/CleoMenezes/Custom-Adwaita-Folder-Icons/commit/fbc6961e2f7d6c8a1f5bac1974d7eb213a27e40f
