### ISSUE TITLE
Icon sizes inconsistent

### ISSUE THREAD

**Issue by mike2307** [CleoMenezes/Custom-Adwaita-Folder-Icons#2]
Some of the icons are too big.
I noticed that at least for the synchronizing and microphone icons; the code icon is fine though.
In my opinion all of the icons should have the same size as the code icon.

Thanks in advance.

**Comment by CleoMenezesJr** [comment]
Hey there! I standardized all the icons on the grid and added new icons. I hope it's to your liking now.

**Comment by mike2307** [comment]
Now it's perfect. Thanks :+1:
