### ISSUE TITLE
Add a new Emacs icon and a rust one as well.

### ISSUE THREAD

**Issue by pacberries** [CleoMenezes/Custom-Adwaita-Folder-Icons#3]
That´s the only thing preventing me from installing this icon set on my system.

**Comment by CleoMenezesJr** [comment]
I just added. You can have a look here: https://github.com/CleoMenezes/Custom-Adwaita-Folder-Icons/commit/484def863e86e1d2246515c2253a8bcd748f1f36

**Comment by pacberries** [comment]
Thank you!
